spring.application.name=api-photo-sharing
spring.mongodb.uri=mongodb+srv://huy0132004:huy153684@apps-cluster.coomzeq.mongodb.net/test_huy

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=file:public/images/